# 实验报告
    实验题目：Python基础知识
    
    班级：              学号：             姓名：        日期：2023.5.10

（注：请将报告转换成HTML格式再提交）
# 一、实验目的

1. 掌握Python的基础语法；

2. 掌握Python的数据类型包括列表、字典、集合等的使用；

3. 熟悉控制结构包括分支、循环、函数等的使用；

3. 掌握Numpy基础知识。

# 二、实验内容

## 1. python基础语法

（1）‘10/3'，‘10//3’和'10%3'结果相同么？请说明原因。

In [22]:
print(10/3)
print(10//3)
print(10%3)

3.3333333333333335
3
1


（2）string1='I'm a student.' 。print(string1)结果会报错么？如何修改string1使其得到正确的输出？

In [26]:
string1='I\'m a student.'
print(string1)

I'm a student.


（3） a = 3，str(a\*3) + str(a)\*3的输出是什么?

In [27]:
a = 3
print(str(a*3) + str(a)*3)

9333


（4）my_string = 'this is my string', 如何查看这个字符串长度？

In [71]:
my_string = 'this is my string'
len(my_string)

17

## 2. 列表、字典、集合

（1）L=[1,2,3,4,1,4,5,6],请完成：①删除列表中的重复元素；②将7添加到列表中；③删除元素3.

In [28]:
L=[1,2,3,4,1,4,5,6]
m=list(set(L))
m

[1, 2, 3, 4, 5, 6]

In [2]:
m.append(7)#insert(6,7)

In [3]:
m

[1, 2, 3, 4, 5, 6, 7]

In [45]:
m.remove(3)
m

[1, 2, 5, 6, 7]

（2）dog = ["tom", "jack", "Collie", "Marry"], kitty = "Marry", 如何判断 kitty 是否是 dog 中的一员?

In [2]:
#使用in判断 kitty 是否是 dog 中的一员
dog = ["tom", "jack", "Collie", "Marry"]
kitty = "Marry"
if kitty in (dog):
    print('因此kitty 是 dog 中的一员')

因此kitty 是 dog 中的一员


（3）dog = ["tom", "jack", "Collie", "Marry"]，将dog逆序。

In [4]:
dog = ["tom", "jack", "Collie", "Marry"]
dog.reverse()
dog[::-1]

['tom', 'jack', 'Collie', 'Marry']

（4）L=[1,2,3,1,5,11,3,6,4,2,5,8,4,2],计算L的最大值、最小值，加和。

In [7]:
L=[1,2,3,1,5,11,3,6,4,2,5,8,4,2]
m=max(L)
n=min(L)
print(m)
print(n)
sum(L)

11
1


57

（5）cube：length：40，width：40，height：40, 请创建一个字典，包括cube的所有信息，并向字典中添加条目“color”和对应值"red"，删除属性height，修改属性width为20.

In [29]:
cube = {'length':40,'width':40,'height':40}
cube['color'] = 'red'
cube.pop('height')
cube['width']  =20
cube

{'length': 40, 'width': 20, 'color': 'red'}

（6）set_a = {1, 5, 10} set_b = {1, 10, 12} 找出set_a和set_b中共有的元素（交集）。

In [9]:
set_a = {1, 5, 10}
set_b = {1, 10, 12}
print("共有元素为：")
print(set_a & set_b)
print(set_a.intersection(set_b))

共有元素为：
{1, 10}
{1, 10}


（7）从1到100中选出所有的奇数。

In [30]:
a=list(range(100))
a[1::2]

[1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99]

## 3. 条件判断、循环和函数

（1）L=[1,2,'','my',3,'name','is',4,'katty'],利用循环语句和判断条件，分别输出列表中的字符串和数字。

In [3]:
L=[1,2,'','my',3,'name','is',4,'katty']
for i in L:
    if type(i)==int :
        print(i)
for i in L:
    if type(i)==str :
        print(i)

1
2
3
4

my
name
is
katty


（2）利用循环语句输出1到50中5的倍数，将其存放到一个列表中。

In [13]:
li=[]
for i in range(1,51):
    if i%5==0:
       li.append(i)
print(li) 

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


（3）定义一个判断字符串的长度是否大于10的函数。

In [4]:
def strlen(str):
    return len(str)>10
strlen('sddfgdfgfdgfdgfdgfdfsd')

True

（4）定义一个求解阶乘的函数；利用列表生成式，生成1-5的阶乘。

In [36]:
import numpy as np
import pandas as pd
from functools import reduce
def factorial(n):
    L = np.arange(1,n+1)
    return reduce(lambda x,y:x*y,L)


In [5]:
#或
def f(n):
    if n==1 or n==0:
        return 1
    else:
        return n*f(n-1)


In [38]:
[f(i+1) for i in range(5)]

[1, 2, 6, 24, 120]

（5）利用函数和列表生成式，标记一个列表，奇数标记为1，偶数标记为2，并且统计一下奇数和偶数的数量。
     例如：[1,4,2,4,2,9,5]，得到[1,2,2,2,2,1,1]

In [40]:
def func(i):
    if i%2==0:
        return 2
    else:
        return 1
l = [1,4,2,4,2,9,5]
 

r=[func(i) for i in l]
r

[1, 2, 2, 2, 2, 1, 1]

In [41]:
print(r.count(2))
print(r.count(1))

4
3


# 4. Numpy的使用

(1)创建一个1到10的数组，然后逆序输出。(#逆序用切片   a[::-1])

In [1]:
import numpy as np
a=np.array(range(1,11))
print(a)
a[::-1]

[ 1  2  3  4  5  6  7  8  9 10]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

(2)从1到10中随机选取10个数，构成一个长度为10的数组，选出其中的奇数。(#bool数组，花式索引）

In [2]:
a=np.random.randint(1,10,10)
a

array([5, 2, 8, 3, 3, 9, 5, 1, 9, 2])

In [3]:
a[a%2==1]

array([5, 3, 3, 9, 5, 1, 9])

(3)在数组[1, 2, 3, 4, 5]中相邻两个数字中间插入1个0。（切片赋值）

In [4]:
a=[1,2,3,4,5]
b=np.zeros(9)
b[::2]=a
b

array([1., 0., 2., 0., 3., 0., 4., 0., 5.])

(4)创建一个长度为10的随机向量，并求其累计和。(np.random.randint,cumsum函数)

In [5]:
a = np.random.randint(1,10,10)
a

array([4, 7, 4, 1, 3, 7, 4, 5, 6, 5])

In [6]:
b=a.cumsum()
b

array([ 4, 11, 15, 16, 19, 26, 30, 35, 41, 46], dtype=int32)